#!/usr/bin/env bash

changelog () {
    clog_cmd="${1}"
    clog_message="${2}"
    log_file=$(clog entry "$clog_cmd" "$clog_message" | grep "create changelogs" | awk '{print $2}')
    echo ">> Changelog file: ${log_file}"
    owner_repo=$(git remote get-url origin | sed -E 's#.*:([^/]+/[^/]+)\.git#\1#')
    echo ">> Running on repo ${owner_repo}"
    pr_number=$(gh pr list --repo $owner_repo --state all --limit 1 --json number --jq '.[0].number')
    pr_number=$((pr_number + 1))
    echo ">> Next pr_number ${pr_number}"
    echo "pr_number: ${pr_number}" >> ${log_file}
    git add changelogs/
    git commit -m "chore: Adding changelog"
    echo ">> pr_number added!"
}
